---
title: "Portfolio 1"
---

---
title: "PULSE Value Ranking Visualization"
output: html_document
date: "2026-02-22"
---

```{r load-packages}
library(haven)
library(tidyverse)
data<-read.csv("/Users/tiffani/Downloads/Project PULSE - Study 1 (Tiffani)_December 18, 2025_09.18_clean.csv")
data <- data %>% 
  select("values_1", "values_2", "values_3", "values_4", "values_5", "values_6", "values_7", "values_8", "values_9", "values_99")
  data <- data [-c(1,2),]
```

```{r covert-data-long}
names(data) <- c("academic_performance", "academic_growth", "absenteeism", "racial_diversity", "special_programming", "convenience", "leadership", "mission_statement", "economic_diversity", "other")
library(tidyverse)
values_long <- data %>%
  pivot_longer(
    cols = everything(),
    names_to = "value",
    values_to = "rank"
  )
values_long <- values_long %>%
  mutate(rank = as.numeric(rank)) %>%
  filter(rank >= 1 & rank <= 10)
```

```{r create-plot}
ggplot(values_long,
       aes(x = reorder(value, rank, FUN = mean),
           y = rank)) +
  geom_boxplot() +
  coord_flip() +
  scale_y_reverse(breaks = 1:10) +
  labs(
    x = "Value",
    y = "Rank (1 = Most Important)",
    title = "Distribution of Value Rankings"
  ) +
  theme_classic()
