---
title: "Portfolio 10"
---

Goal: The goal of this portfolio piece is to create graphics for descriptive statistics of parents in the first study of my thesis.

```{r load-packages, echo = FALSE, message=FALSE}
library(readr)
library(haven)
library(dplyr)
library(tidyverse)
library(ggplot2)
```
```{r read-data, echo=FALSE, message=FALSE}
pulse <- read.csv("/Users/tiffani/Downloads/Project PULSE - Study 1 (Tiffani)_December 18, 2025_09.18_clean.csv")
```
```{r create-plots-of-demos, echo = FALSE, message=FALSE}
pulse$parent_political_1 <- as.numeric(pulse$parent_political_1)

pulse %>% 
  ggplot(aes(x = parent_political_1))+
  geom_bar() +
  coord_flip() +
  labs(x = "Political Affiliation (1 = Liberal to 7 = Conservative)",
       y = "Number of Parents")

pulse$parent_education <- as.numeric(pulse$parent_education)

pulse %>% 
  filter(parent_education != 99) %>% 
  ggplot(aes(x = parent_education)) +
  geom_bar() + 
  coord_flip(ylim = c(0,50)) +
  labs(x = "Parent Education Level",
       y = "Number of Parents") +
  scale_x_continuous(breaks = seq(0, 10, by = 1))

pulse %>% 
  filter(parent_ses %in% c(1:6) ) %>% 
  ggplot(aes(x = parent_ses)) +
  coord_flip() +
  geom_bar() +
  labs(x = "Socioeconomic Status",
       y = "Number of Parents")
  
```